pub const HELP_MESSAGE: &str = "## HODGEY BOT COMMAND LIST\n\n### Hodgey Help\nGives the list of commands for Hodgey bot.\n### @Someone\nIf used anywhere in the message a random user will be pinged.\n### Hodgey Joke\nHodgey bot tell's you a joke.\n### Hodgey Help Chess\nGives the list of chess commands.";
/*
parts from old help message
\n### Set Message Channel\nSets the channel for my random messages (you need to be a mod)\n### Remove Message Channel\nRemoves the channel for my random messages (you need to be a mod)\n### Hodgey Stats\nGives some stats about hodgey bot\n### Hodgey Bot Suggestion\nsuggest a feature or improvement for Hodgey Bot
*/
pub const CHESS_HELP_MESSAGE: &str = "## HODGEY BOT CHESS COMMAND LIST\n\n### Chess New\nStarts a new chess game. To play against another person ping them at the end of the message.\n### Move\nLets you make a move. Examples: \"Move e4\", \"Move Nc6\", \"Move e2 e4\". To promote a piece you must use algebraic notation such as \"Move e8Q\" to promote to queen.\n### Chess Show\nShows your current chess game.\n### Toggle Coordinates\nDisables or enables coordinates.\n### Toggle Board Flip\nDisables or enables the board flipping on black's turn.";
pub const NO_ACTIVE_CHESS_GAME: &str = "You don't have an active chess game. Start a new one with \"Chess New\"";
pub const MEE6: [&str; 3] = ["SHUT UP MEE6!", "Get stuffed MEE6!", "MEE6, more like bad!"];
pub const BUSY: [&str; 2] = ["playing chess", "listening to Green Day"];
pub const CHESS: [&str; 14] = ["CHESS!", "Google en passant", "Did someone say chess?", "Chess is way better than checkers", "Is that a free juicer?", "I just won my chess game", "I just lost my chess game", "I just en passanted some guy", "I am completely winning", "Takes takes takes", "Chess good, checkers bad", "It’s fun dominating kids on chesskids.com", "Add me on Chess.com <https://www.chess.com/member/h-o-d-g-e-y>", "I am going to sac for the content"];
pub const CHECKERS: [&str; 5] = ["Checkers is bad", "I hate checkers", "Chess good, checkers bad", "People who play checkers might need some help", "Checkers is the worst thing since roblox"];
pub const BOOKS: [&str; 21] = ["Needful Things", "The Green Mile", "Different Seasons", "Raven’s Gate", "The Shining", "And Then There Were None", "The Stand", "1984", "The Book Thief", "11/22/63", "The Hunger Games", "Letters from Berlin", "The Queen's Gambit", "The Dead Zone", "Hush Hush", "The Hobbit", "The Maze Runner", "The Jedi Path", "Warwick Todd", "Billy Summers", "Sherlock Holmes"];
pub const SONG_STARTS: [&str; 6] = ["Have you listened to SONG?", "Have you heard SONG?", "I really like SONG", "I have been listening to SONG", "SONG is the best!", "I'm sure SONG is better than that"];
pub const SONGS: [&str; 146] = ["Sweet Child o Mine", "Patience", "When I Come Around", "Whatsername", "Pulling Teeth", "Scattered", "Prosthetic Head", "Good Riddance (Time Of Your Life)", "Basket Case", "21 Guns", "21st Century Breakdown", "Suspicious Minds", "Burning Love", "In The Ghetto", "I've Got A Thing About You Baby", "Hotel California", "Jolene", "I Will Always Love You", "Brimful Of Asha", "Johnny B Goode", "You Can Never Tell", "Visions Of Johanna", "The Times They Are A Changin", "Tangled Up In Blue", "Sad Eyed Lady Of The Lowlands", "Queen Jane Approximately", "Positively 4th Street", "One Of Us Must Know (Sooner Or Later)", "Not Dark Yet", "Mr Tambourine Man", "Most Of The Time", "Masters Of War", "Love Minus Zero", "Like a Rolling Stone", "Knockin' On Heavens Door", "It's Alright Ma (I'm Only Bleeding)", "It's All Over Now Baby Blue", "It Ain't Me Babe", "Hurricane", "A Hard Rains A-Gonna Fall", "Blowing In The Wind", "Vienna", "Mama Kin", "Sweet Emotion", "Son Of A Preacher Man", "Don't Worry Baby", "Back In The USSR", "Blackbird", "Dig A Pony", "Drive My Car", "Let It Be", "Hey Jude", "Norwegian Wood", "Octopus' Garden", "Twist and Shout", "Yesterday", "Highwayman", "1955", "The Hard Road", "I Love it", "The Nosebleed Section", "Shredding The Balloon", "Blunderbuss", "Hip (Eponymous) Poor Boy", "Getting Away With It (All Messed Up)", "Laid", "House Carpenter", "All Along The Watchtower", "Castles Made Of Sand", "Hey Joe", "Voodoo Child (Slight Return)", "Hurt", "Stand By Me", "Cry In Shame", "Lola", "Stop Your Sobbing", "A Rock N Roll Fantasy", "Waterloo Sunset", "The Battle Of Evermore", "Going To California", "Stairway To Heaven", "Short Memory", "What A Wonderful World", "Walk On The Wild Side", "Wonderwall", "The Devil Went Down To Georgia", "Graceland", "Me And Julio Down By The Schoolyard", "Fat Bottomed Girls", "Hammer To Fall", "I Want It All", "Killer Queen", "Love Of My Life", "Radio Gaga", "Under Pressure", "Getting Away (From this world)", "That Ain't Bad", "I Was Only 19", "Longrun", "Orange Crush", "Losing My Religion", "Stand", "Angie", "Brown Sugar", "Monkey Man", "Ruby Tuesday", "She's A Rainbow", "Start Me Up", "Sway", "Sympathy for the Devil", "Wild Horses", "You Can't Always Get What You Want", "Take Your Mama", "Venus ", "America", "The Boxer", "Faking It", "Bridge Over Troubled Water", "Cecila", "Mrs Robinson", "The Only Living Boy In New York", "The Sound Of Silence", "1979", "Today ", "Cherub Rock", "Glockenpop", "End Of The Line", "Handle With Care", "Happy Together", "Lost In Love", "You're The One", "Buddy Holly", "Holiday", "Island In The Sun", "My Name Is Jonas", "say it aint so", "you might think", "forever for her (is over for me)", "Hotel Yorba", "I'm Bound To Pack It Up", "My Doorbell", "Same Boy You Have Always Known", "You Don't Know What Love Is", "Pinball Wizard", "squeezebox", "Live And Let Die"];
pub const MOVIES: [&str; 17] = ["Cars 2", "Shawshank Redemption", "The Dark Knight", "Futurama", "The Office UK", "The Castle", "The Dish", "The Queen's Gambit", "The Green Mile", "Tenet", "Saving Private Ryan", "Backyard Ashes", "Pulp Fiction", "Frontline", "Terminator 2", "The Hollowmen", "Interstellar"];
pub const RANDOM: [&str; 40] = ["I've got to go my phone is on 1%", "I disagree", "^ @here", "I have been carrying Jackson at Valorant", "You should get my haircut", "How's it going old buddy old pal?", "Mods bad", "I lost the game", "Did you ever hear the tragedy of darth plagueis the wise?", "Chess good, checkers bad", "I just won my chess game", "I just lost my chess game", "We don't need this channel", "Indeed", "^", "Lmao", "I agree", "It’s fun dominating kids on chesskids.com", "Someone play chess with me", "thats the spirit", "Calm your farm", "Hold the phone", "Bye bye wallet, bye bye keys", "Gonski", "I need aami roadside assistance", "Fair call", "A \"fair\" counter", "Oi yoi yoi", "Here we go", "Just another day at the office", "Rookie mistake there", "Let’s party like it’s on sale for $19.99", "close but no cigar", "Back in the good old days", "Back in my day", "What can possibly go wrong", "Free discord nitro!", "Too weak, too slow!", "👲", "Is this a Jojo reference?"];
//const profileChangeQuotes = ['I liked your old %THING% :(', 'I like your new %THING% :D', 'Your new %THING% sucks.', 'Your new %THING% is good.', "That's an awesome %THING%!"];
//const newUserQuotes = [`Who is %USER%?`, `I hope you are here to play chess with me %USER%.`];
pub const NEW_CHANNEL: [&str; 5] = ["Why did we need another channel?", "First!", "We needed this channel", "We didn't need this channel", "I have been waiting for this channel"];
//const noQuotes = ["No, I don't want to", "Stop asking me to"]
//const DELETED_CHANNEL_QUOTES = ["That was my favourite channel :(", "I liked that channel :("];
pub const DECISION: [&str; 14] = ["Yes", "No", "Yes!", "No!", "Yeah nah", "Nah yeah", "Affirmative", "Negative", "I agree", "I disagree", "You are wrong", "You are right", "That is true", "That is false"];
//const chessMoves = ['d4', 'e6', 'e4', 'd5', 'c3', 'c5', 'f3', 'c6', 'exd5', 'exd5', 'e2', 'f6', 'O-O', 'dxc5', 'e6', 'd4', 'xc5', 'xe6', 'fxe6', 'g4', 'd6', 'h3', 'ae8', 'd2', 'b4', 'xf6', 'xf6', 'ad1', 'c5', 'e2', 'xc3', 'bxc3', 'xc3', 'xd5', 'd4', 'h5', 'ef8', 'e5', 'h6', 'g5', 'xh3', 'g5', 'xh3', 'c5', 'g3'];
pub const VAL_AGENTS: [&str; 24] = ["Astra", "Breach", "Brimstone", "Chamber", "Clove", "Cypher", "Deadlock", "Fade", "Gekko", "Iso", "Jett", "KAY/O", "Killjoy", "Neon", "Omen", "Phoenix", "Raze", "Reyna", "Sage", "Skye", "Sova", "Viper", "Yoru", "Harbor"];